### PR TITLE
Enhance architecture to address cyclic dependencies in magellan-server and magellan-client

### LINKED ISSUE #22: Cyclic module dependencies in client / server between transport and configuration/services
# Bug Report

Currently, there are cyclic dependencies between `src/transport` and `src/configuration` / `src/services` which express themselfes through the need to mock `formdataFetch` in client/src/config/configuration-repository.spec.ts, server/src/config/configuration-repository.spec.ts and server/src/services/FunctionService.spec.ts (see commit https://github.com/quatico-solutions/magellan/pull/20/commits/59e6f5c507f08c549f51667c9a87a1230c5bc996)

This will negatively impact the ability to chunk code with @quatico/magellan-client and @quatico/magellan-server dependencies.

### 🔎 Search Terms

- cyclic dependency
- "formdataFetch" not initialized

### 🕗 Version & Regression Information

After replacing the ts-jest transformer with @swc/jest

### 🙁 Actual behavior

formdata-fetch => formdataFetch mocks are necessary to execute jest tests with @swc/jest.

### 🙂 Expected behavior

tests do not require to mock away the dependency on formdataFetch to avoid issues with cyclic dependencies.

### PR DESCRIPTION
**Pull request by dreamora**

### CODE REVIEW

File: packages/client/src/transport/formdata-fetch.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@
  * ---------------------------------------------------------------------------------------------
  */
 import { TransportFunction, TransportHandler } from "@quatico/magellan-shared";
-import type { Context } from "../configuration";
+import type { Context } from ".";
```
Comment (jwloka) [inline packages/client/src/transport/formdata-fetch.ts]: Don't import from your module's index file

File: packages/client/src/transport/namespace.ts [hunk 2]
```diff
@@ -6,7 +6,7 @@
  */
 import type { NamespaceMapping, TransportHandler } from "@quatico/magellan-shared";
 import { assert } from "@quatico/magellan-shared";
-import { formdataFetch } from "../transport";
+import { formdataFetch } from ".";
```
Comment (jwloka) [inline packages/client/src/transport/namespace.ts]: Don't import from your module's index file

File: packages/client/src/transport/transport-request.ts [hunk 3]
```diff
@@ -4,8 +4,8 @@
  *   Licensed under the MIT License. See LICENSE in the project root for license information.
  * ---------------------------------------------------------------------------------------------
  */
-import type { Context } from "../configuration";
-import { resolveNamespace } from "../configuration";
+import type { Context } from ".";
+import { resolveNamespace } from ".";
```
Comment (jwloka) [inline packages/client/src/transport/transport-request.ts]: Don't import from your module's index file

**Review by jwloka — COMMENTED** [review]
Can you fix the import from same module's index comments?!

**Review by jwloka — APPROVED** [review]
Looks good. Thanks a lot!
